vim.cmd.source("~/.config/nvim/lua/configs/coc.vim")
vim.cmd.source("~/.config/nvim/lua/configs/conjure.vim")
require("configs.fennel-language-server")
require("configs.fzf")
vim.cmd.source("~/.config/nvim/lua/configs/vim-iced.vim")
require("configs.marks")
require("configs.neotree")
require("configs.oil")
require("configs.treesitter")
-- vim.cmd.source("~/.config/nvim/lua/configs/vim-iced.vim")
