require("configs.conjure")
require("configs.noice")
require("configs.deno")
require("configs.fennel-language-server")
require("configs.fzf")
require("configs.marks")
require("configs.oil")
require("configs.dap")
-- require("configs.treesitter")
