-- require("dap").adapters["pwa-node"] = {
--   type = "server",
--   host = "localhost",
--   port = "${port}",
--   executable = {
--     command = "node",
--     -- 💀 Make sure to update this path to point to your installation
--     args = {"~/code/node/vscode-js-debug-1.77.2/src/debugServerMain.ts", "${port}"},
--     -- args = {"/path/to/js-debug/src/dapDebugServer.js", "${port}"},
--   }
-- }
